---
# tasks file for valo_web
- name: install nginx
  apt:
    name: nginx
    state: present

- name: start nginx
  systemd: 
    name: nginx
    state: started
    enabled: yes

- name: clean
  shell: rm -rf /var/www/html/*

- name: pages machine
  template:
    src: "{{ item.src }}"
    dest: "/var/www/html/{{ item.dest }}"
  delegate_to: 10.88.0.32 
  with_items:
  - { src: "index.html.j2", dest: "index.html" }
  - { src: "style.css.j2", dest: "style.css" }

- name: pages machine
  template:
    src: servers.html.j2
    dest: /var/www/html/server-{{ ansible_hostname }}.html
  delegate_to: 10.88.0.32
